### ISSUE TITLE
RFC: Project setup fixes

### ISSUE THREAD

**Issue by samderanova** [HackAtUCI/zothacks-site-2023#2]
If there are any recommendations or issues regarding the setup of this project in terms of file structure, ESLint, Prettier, etc., these should be addressed in this task. Otherwise, we can close this issue.

The purpose of this issue is so that moving forward, we all agree on one configuration and won't need to deal with serious merge conflicts as a result.

**Comment by taesungh** [comment]
Personal preference on page layout: following up from #1, having all of our page components in a file named `page.js` could be confusing and less efficient for file navigation (e.g. Quick Open on VS Code). One alternative in my mind is having separate component files and reexporting the default component in `page.js`, but this might not be helpful in all cases.

**Comment by samderanova** [comment]
Closed as completed in #8 . Any other related changes that are needed should now be made by opening a new issue.
