### ISSUE TITLE
Import fonts, styles, and assets into project space

### ISSUE THREAD

**Issue by samderanova** [HackAtUCI/zothacks-site-2023#3]
Please refer to [the Figma design](https://www.figma.com/file/XEOFje2scrEW6SpLR5ono6/ZotHacks-2023-Site-Planning?type=design&node-id=0-1&mode=design&t=eeuzQNtN09BrwD7L-0). The font to be used, colors, assets, and designs can all be found here.

Each color should be stored in a SCSS file as a variable and any assets should be stored in a folder.

**Note:** When downloading assets, please make sure that they are all SVGs if possible, as we prefer vector graphics over raster ones.

**Comment by tyleryy** [comment]
I imported the fonts and colors from the Figma project, but there was one color hex value mismatch. So, i'll sync up with graphics to fix it. I'll look into importing the assets into Sanity.

**Comment by tyleryy** [comment]
I've set up a rough draft of what our Sanity schema should be like. Please review my changes because I am new to Sanity, and my changes can probably be optimized or written better in some way. Thanks!

**Comment by samderanova** [comment]
Closing this issue as it has been completed in #2 .
