### ISSUE TITLE
Fix dead zone created by heart sticker over Apply button

### ISSUE THREAD

**Issue by taesungh** [HackAtUCI/zothacks-site-2023#49]
The container used to hold the heart sticker leaves a dead zone behind even after the heart sticker is dragged. As such, the Apply button cannot be clicked in that spot.

**Comment by tyleryy** [comment]
I fixed this in the sticker enhancements branch

**Comment by samderanova** [comment]
> I fixed this in the sticker enhancements branch

Sorry, just saw this comment! Will link yours to this issue
