### ISSUE TITLE
Encrypted routes

### ISSUE THREAD

**Issue by tyleryy** [HackAtUCI/zothacks-site-2023#85]
Create routes that are long strings for the resource and schedule page, but keep the navbar disabled. That way we can still access the routes with the navbar disabled and prevent users from seeing the unfinished routes on prod.

**Comment by samderanova** [comment]
Talked to @taesungh about this, we should just make the routes public but exclude them from the navbar.

**Comment by taesungh** [comment]
Feature flags implemented with environment variables in #40.
